### ISSUE TITLE
Selbst definierte Abspiel-Sets gehen nach Update scheinbar verloren

### ISSUE THREAD

**Issue by jolinux** [xaverW/P2Radio#1]
Hallo,

nach einem Update auf Version 6 ist wohl  mein selbst definiertes Set fürs Abspielen mit einem anderen Player vollständig raus geflogen.

Jörg

**Comment by xaverW** [comment]
Das ist kein Fehler. Die Sets wurden vereinfacht und durch die Änderungen konnten die alten Sets leider nicht korrekt übernommen werden. Es wird deswegen mit den Standardsets gestartet und deswegen kommt auch die Meldung, diese zu überprüfen.
